// Group 59
// ----------------------------------
// Muhammad Tayyab Rashid - a1988298
// Nguyen Duc Tung Bui - a1976012
// Guilin Luo - a1989840
// Mazharul Islam Rakib - a1990942
// Masud Ahammad - a1993200

export const MESSAGE_TYPES = Object.freeze({
  USER_HELLO: 'USER_HELLO',
  USER_DELIVER: 'USER_DELIVER',
  MSG_DIRECT: 'MSG_DIRECT',
  MSG_PUBLIC_CHANNEL: 'MSG_PUBLIC_CHANNEL',
  PUBLIC_CHANNEL_ADD: 'PUBLIC_CHANNEL_ADD',
  PUBLIC_CHANNEL_UPDATED: 'PUBLIC_CHANNEL_UPDATED',
  PUBLIC_CHANNEL_KEY_SHARE: 'PUBLIC_CHANNEL_KEY_SHARE',
  COMMAND_RESPONSE: 'COMMAND_RESPONSE',
  COMMAND: 'COMMAND',
  FILE_START: 'FILE_START',
  FILE_CHUNK: 'FILE_CHUNK',
  FILE_END: 'FILE_END',
  USER_ADVERTISE: 'USER_ADVERTISE',
  USER_REMOVE: 'USER_REMOVE',
  SERVER_DELIVER: 'SERVER_DELIVER',
  HEARTBEAT: 'HEARTBEAT',
  ERROR: 'ERROR',
});

export default MESSAGE_TYPES;
